
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HSeparator hseparator4;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.VSeparator vseparator4;
	
	private global::Gtk.Button button6;
	
	private global::Gtk.VSeparator vseparator6;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.VSeparator vseparator5;
	
	private global::Gtk.Button button7;
	
	private global::Gtk.Button button5;
	
	private global::Gtk.Button button4;
	
	private global::Gtk.VSeparator vseparator3;
	
	private global::Gtk.HSeparator hseparator1;
	
	private global::Gtk.HPaned hpaned2;
	
	private global::Gtk.VBox vbox10;
	
	private global::Gtk.HBox hbox12;
	
	private global::Gtk.VSeparator vseparator1;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.ComboBox combobox4;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.Button button1;
	
	private global::Gtk.Button button2;
	
	private global::Gtk.Button button20;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.NodeView nodeview1;
	
	private global::Gtk.VBox vbox11;
	
	private global::Gtk.HBox hbox13;
	
	private global::Gtk.Button button24;
	
	private global::Gtk.VBox vbox12;
	
	private global::Gtk.Button button22;
	
	private global::Gtk.Button button23;
	
	private global::Gtk.VSeparator vseparator2;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.ComboBox combobox1;
	
	private global::Gtk.Button button3;
	
	private global::Gtk.VSeparator vseparator10;
	
	private global::Gtk.Notebook notebook1;
	
	private global::Gtk.VBox vbox13;
	
	private global::Gtk.HBox hbox14;
	
	private global::Gtk.Label label10;
	
	private global::Gtk.ComboBox combobox5;
	
	private global::Gtk.Button button25;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	
	private global::Gtk.NodeView nodeview2;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	
	private global::Gtk.NodeView nodeview3;
	
	private global::Gtk.Label label7;
	
	private global::Gtk.Label label8;
	
	private global::Gtk.Label label9;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.ProgressBar progressbar4;
	
	private global::Gtk.HSeparator hseparator6;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.VSeparator vseparator8;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.ProgressBar progressbar3;
	
	private global::Gtk.VSeparator vseparator9;
	
	private global::Gtk.Label label11;
	
	private global::Gtk.ProgressBar progressbar5;
	
	private global::Gtk.VSeparator vseparator7;
	
	private global::Gtk.HSeparator hseparator5;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("IRIS Launcher");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource ("IRISLauncher.IRISLauncher.ico");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hseparator4 = new global::Gtk.HSeparator ();
		this.hseparator4.Name = "hseparator4";
		this.vbox1.Add (this.hseparator4);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator4]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vseparator4 = new global::Gtk.VSeparator ();
		this.vseparator4.Name = "vseparator4";
		this.hbox2.Add (this.vseparator4);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vseparator4]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button6 = new global::Gtk.Button ();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString ("Settings");
		this.hbox2.Add (this.button6);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button6]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vseparator6 = new global::Gtk.VSeparator ();
		this.vseparator6.Name = "vseparator6";
		this.hbox2.Add (this.vseparator6);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vseparator6]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("IRIS Launcher");
		this.label2.Justify = ((global::Gtk.Justification)(2));
		this.hbox2.Add (this.label2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label2]));
		w5.Position = 3;
		w5.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vseparator5 = new global::Gtk.VSeparator ();
		this.vseparator5.Name = "vseparator5";
		this.hbox2.Add (this.vseparator5);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vseparator5]));
		w6.Position = 4;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button7 = new global::Gtk.Button ();
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString ("Problems");
		this.hbox2.Add (this.button7);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button7]));
		w7.Position = 5;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button ();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString ("Updates");
		this.hbox2.Add (this.button5);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button5]));
		w8.Position = 6;
		w8.Expand = false;
		w8.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button ();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString ("Help");
		this.hbox2.Add (this.button4);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button4]));
		w9.Position = 7;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vseparator3 = new global::Gtk.VSeparator ();
		this.vseparator3.Name = "vseparator3";
		this.hbox2.Add (this.vseparator3);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vseparator3]));
		w10.Position = 8;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.Name = "hseparator1";
		this.vbox1.Add (this.hseparator1);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hpaned2 = new global::Gtk.HPaned ();
		this.hpaned2.CanFocus = true;
		this.hpaned2.Name = "hpaned2";
		this.hpaned2.Position = 338;
		// Container child hpaned2.Gtk.Paned+PanedChild
		this.vbox10 = new global::Gtk.VBox ();
		this.vbox10.Name = "vbox10";
		this.vbox10.Spacing = 6;
		// Container child vbox10.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox ();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.vseparator1 = new global::Gtk.VSeparator ();
		this.vseparator1.Name = "vseparator1";
		this.hbox12.Add (this.vseparator1);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.vseparator1]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Instance");
		this.hbox12.Add (this.label5);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.label5]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.combobox4 = global::Gtk.ComboBox.NewText ();
		this.combobox4.Name = "combobox4";
		this.hbox12.Add (this.combobox4);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.combobox4]));
		w15.Position = 2;
		// Container child hbox12.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Load Instance");
		this.vbox2.Add (this.button1);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button1]));
		w16.Position = 0;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("Edit Instance");
		this.vbox2.Add (this.button2);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.button2]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		this.hbox12.Add (this.vbox2);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.vbox2]));
		w18.Position = 3;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox12.Gtk.Box+BoxChild
		this.button20 = new global::Gtk.Button ();
		this.button20.CanFocus = true;
		this.button20.Name = "button20";
		this.button20.UseUnderline = true;
		this.button20.Label = global::Mono.Unix.Catalog.GetString ("Download Instance");
		this.hbox12.Add (this.button20);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.button20]));
		w19.Position = 4;
		w19.Expand = false;
		w19.Fill = false;
		this.vbox10.Add (this.hbox12);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox12]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.nodeview1 = new global::Gtk.NodeView ();
		this.nodeview1.CanFocus = true;
		this.nodeview1.Name = "nodeview1";
		this.GtkScrolledWindow.Add (this.nodeview1);
		this.vbox10.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.GtkScrolledWindow]));
		w22.Position = 1;
		this.hpaned2.Add (this.vbox10);
		global::Gtk.Paned.PanedChild w23 = ((global::Gtk.Paned.PanedChild)(this.hpaned2 [this.vbox10]));
		w23.Resize = false;
		// Container child hpaned2.Gtk.Paned+PanedChild
		this.vbox11 = new global::Gtk.VBox ();
		this.vbox11.Name = "vbox11";
		this.vbox11.Spacing = 6;
		// Container child vbox11.Gtk.Box+BoxChild
		this.hbox13 = new global::Gtk.HBox ();
		this.hbox13.Name = "hbox13";
		this.hbox13.Spacing = 6;
		// Container child hbox13.Gtk.Box+BoxChild
		this.button24 = new global::Gtk.Button ();
		this.button24.CanFocus = true;
		this.button24.Name = "button24";
		this.button24.UseUnderline = true;
		this.button24.Label = global::Mono.Unix.Catalog.GetString ("Play");
		this.hbox13.Add (this.button24);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.button24]));
		w24.Position = 0;
		// Container child hbox13.Gtk.Box+BoxChild
		this.vbox12 = new global::Gtk.VBox ();
		this.vbox12.Name = "vbox12";
		this.vbox12.Spacing = 6;
		// Container child vbox12.Gtk.Box+BoxChild
		this.button22 = new global::Gtk.Button ();
		this.button22.CanFocus = true;
		this.button22.Name = "button22";
		this.button22.UseUnderline = true;
		this.button22.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.vbox12.Add (this.button22);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.button22]));
		w25.Position = 0;
		// Container child vbox12.Gtk.Box+BoxChild
		this.button23 = new global::Gtk.Button ();
		this.button23.CanFocus = true;
		this.button23.Name = "button23";
		this.button23.UseUnderline = true;
		this.button23.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.vbox12.Add (this.button23);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.button23]));
		w26.Position = 1;
		this.hbox13.Add (this.vbox12);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.vbox12]));
		w27.Position = 1;
		w27.Expand = false;
		w27.Fill = false;
		// Container child hbox13.Gtk.Box+BoxChild
		this.vseparator2 = new global::Gtk.VSeparator ();
		this.vseparator2.Name = "vseparator2";
		this.hbox13.Add (this.vseparator2);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.vseparator2]));
		w28.Position = 2;
		w28.Expand = false;
		w28.Fill = false;
		this.vbox11.Add (this.hbox13);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.hbox13]));
		w29.Position = 0;
		w29.Expand = false;
		w29.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Account");
		this.hbox1.Add (this.label1);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
		w30.Position = 0;
		w30.Expand = false;
		w30.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.combobox1 = global::Gtk.ComboBox.NewText ();
		this.combobox1.Name = "combobox1";
		this.hbox1.Add (this.combobox1);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.combobox1]));
		w31.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("Sign In");
		this.hbox1.Add (this.button3);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.button3]));
		w32.Position = 2;
		w32.Expand = false;
		w32.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vseparator10 = new global::Gtk.VSeparator ();
		this.vseparator10.Name = "vseparator10";
		this.hbox1.Add (this.vseparator10);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vseparator10]));
		w33.Position = 3;
		w33.Expand = false;
		w33.Fill = false;
		this.vbox11.Add (this.hbox1);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.hbox1]));
		w34.Position = 1;
		w34.Expand = false;
		w34.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 0;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.vbox13 = new global::Gtk.VBox ();
		this.vbox13.Name = "vbox13";
		this.vbox13.Spacing = 6;
		// Container child vbox13.Gtk.Box+BoxChild
		this.hbox14 = new global::Gtk.HBox ();
		this.hbox14.Name = "hbox14";
		this.hbox14.Spacing = 6;
		// Container child hbox14.Gtk.Box+BoxChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Mod Archive");
		this.hbox14.Add (this.label10);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label10]));
		w35.Position = 0;
		w35.Expand = false;
		w35.Fill = false;
		// Container child hbox14.Gtk.Box+BoxChild
		this.combobox5 = global::Gtk.ComboBox.NewText ();
		this.combobox5.Name = "combobox5";
		this.hbox14.Add (this.combobox5);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.combobox5]));
		w36.Position = 1;
		// Container child hbox14.Gtk.Box+BoxChild
		this.button25 = new global::Gtk.Button ();
		this.button25.CanFocus = true;
		this.button25.Name = "button25";
		this.button25.UseUnderline = true;
		this.button25.Label = global::Mono.Unix.Catalog.GetString ("Add Archive");
		this.hbox14.Add (this.button25);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.button25]));
		w37.Position = 2;
		w37.Expand = false;
		w37.Fill = false;
		this.vbox13.Add (this.hbox14);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.hbox14]));
		w38.Position = 0;
		w38.Expand = false;
		w38.Fill = false;
		// Container child vbox13.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.nodeview2 = new global::Gtk.NodeView ();
		this.nodeview2.CanFocus = true;
		this.nodeview2.Name = "nodeview2";
		this.GtkScrolledWindow1.Add (this.nodeview2);
		this.vbox13.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.GtkScrolledWindow1]));
		w40.Position = 1;
		this.notebook1.Add (this.vbox13);
		// Notebook tab
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Archives");
		this.notebook1.SetTabLabel (this.vbox13, this.label6);
		this.label6.ShowAll ();
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.nodeview3 = new global::Gtk.NodeView ();
		this.nodeview3.CanFocus = true;
		this.nodeview3.Name = "nodeview3";
		this.GtkScrolledWindow2.Add (this.nodeview3);
		this.notebook1.Add (this.GtkScrolledWindow2);
		global::Gtk.Notebook.NotebookChild w43 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.GtkScrolledWindow2]));
		w43.Position = 1;
		// Notebook tab
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Downloads");
		this.notebook1.SetTabLabel (this.GtkScrolledWindow2, this.label7);
		this.label7.ShowAll ();
		// Notebook tab
		global::Gtk.Label w44 = new global::Gtk.Label ();
		w44.Visible = true;
		this.notebook1.Add (w44);
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("page3");
		this.notebook1.SetTabLabel (w44, this.label8);
		this.label8.ShowAll ();
		// Notebook tab
		global::Gtk.Label w45 = new global::Gtk.Label ();
		w45.Visible = true;
		this.notebook1.Add (w45);
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("page4");
		this.notebook1.SetTabLabel (w45, this.label9);
		this.label9.ShowAll ();
		this.vbox11.Add (this.notebook1);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.notebook1]));
		w46.Position = 2;
		// Container child vbox11.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("label3");
		this.hbox4.Add (this.label4);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label4]));
		w47.Position = 0;
		w47.Expand = false;
		w47.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.progressbar4 = new global::Gtk.ProgressBar ();
		this.progressbar4.Name = "progressbar4";
		this.hbox4.Add (this.progressbar4);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.progressbar4]));
		w48.Position = 1;
		this.vbox11.Add (this.hbox4);
		global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.hbox4]));
		w49.Position = 3;
		w49.Expand = false;
		w49.Fill = false;
		this.hpaned2.Add (this.vbox11);
		this.vbox1.Add (this.hpaned2);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hpaned2]));
		w51.Position = 3;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hseparator6 = new global::Gtk.HSeparator ();
		this.hseparator6.Name = "hseparator6";
		this.vbox1.Add (this.hseparator6);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator6]));
		w52.Position = 4;
		w52.Expand = false;
		w52.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vseparator8 = new global::Gtk.VSeparator ();
		this.vseparator8.Name = "vseparator8";
		this.hbox3.Add (this.vseparator8);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vseparator8]));
		w53.Position = 0;
		w53.Expand = false;
		w53.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
		this.hbox3.Add (this.label3);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label3]));
		w54.Position = 1;
		w54.Expand = false;
		w54.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.progressbar3 = new global::Gtk.ProgressBar ();
		this.progressbar3.Name = "progressbar3";
		this.hbox3.Add (this.progressbar3);
		global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.progressbar3]));
		w55.Position = 2;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vseparator9 = new global::Gtk.VSeparator ();
		this.vseparator9.Name = "vseparator9";
		this.hbox3.Add (this.vseparator9);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vseparator9]));
		w56.Position = 3;
		w56.Expand = false;
		w56.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("label4");
		this.hbox3.Add (this.label11);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label11]));
		w57.Position = 4;
		w57.Expand = false;
		w57.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.progressbar5 = new global::Gtk.ProgressBar ();
		this.progressbar5.Name = "progressbar5";
		this.hbox3.Add (this.progressbar5);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.progressbar5]));
		w58.Position = 5;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vseparator7 = new global::Gtk.VSeparator ();
		this.vseparator7.Name = "vseparator7";
		this.hbox3.Add (this.vseparator7);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vseparator7]));
		w59.Position = 6;
		w59.Expand = false;
		w59.Fill = false;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w60.Position = 5;
		w60.Expand = false;
		w60.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hseparator5 = new global::Gtk.HSeparator ();
		this.hseparator5.Name = "hseparator5";
		this.vbox1.Add (this.hseparator5);
		global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator5]));
		w61.Position = 6;
		w61.Expand = false;
		w61.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 700;
		this.DefaultHeight = 460;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
